#pragma once
#ifndef TRAFFIC_STATES_H
#define TRAFFIC_STATES_H

typedef enum {
    TRAFFIC_ALL_RED_EW_TO_NS,
    TRAFFIC_NS_RED_YELLOW,
    TRAFFIC_NS_GREEN,
    TRAFFIC_NS_GREEN_BLINKING,
    TRAFFIC_NS_YELLOW,
    TRAFFIC_ALL_RED_NS_TO_EW,
    TRAFFIC_EW_RED_YELLOW,
    TRAFFIC_EW_GREEN,
     TRAFFIC_EW_GREEN_BLINKING,
    TRAFFIC_EW_YELLOW,
    TRAFFIC_STATE_AMOUNT // 8
} traffic_state_t;

#endif